### ISSUE TITLE
[ERROR] Failed to load resource: the server responded with a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by livevasiliy** [rehmatworks/stisla-laravel#10]
Hello, @rehmatworks ! 
I have problem with loading list users if I start `watch` script from `package.json`. I modif `webpack.mix.js` i added `browser-sync` with proxy on host my local server & `Livereload` for Webpack.
I start `watch` script → Webpack build files → Start browser-sync on `localhost:3000` → I write credientials
email: `admin@example.com` &  password: `1234`. → Navigate `Users` → App try give data from server → I give error `No Results
Looks like you have not added any users yet!` in console browser I got next error in console `Failed to load resource: the server responded with a status of 401 (Unauthorized)`

**Comment by rehmatworks** [comment]
Hello @livevasiliy Can you confirm that you were signed in as well as you populated the database data using the default seeders come with this package?

**Comment by livevasiliy** [comment]
> Hello @livevasiliy Can you confirm that you were signed in as well as you populated the database data using the default seeders come with this package?

Hello @rehmatworks I already solved my problem.
