### ISSUE TITLE
 @yield('scripts') in admin-master.blade.php

### ISSUE THREAD

**Issue by ManojKiranA** [rehmatworks/stisla-laravel#2]
i have downloaded and installed your code I was wondering why are You using

@yield('javascript')

Bacause some of the pages dont have the any other extra js

For that situation

//in some child blade templates

@push('pushName')

@endpush
and in the admin-master.blade.php

@stack('pushName')

**IF POSSIBLE I WILL MAKE PR FOR THAT**

**Comment by rehmatworks** [comment]
Thank you for noticing this out. You can create a PR.
