### ISSUE TITLE
403 This action is unauthorized.

### ISSUE THREAD

**Issue by cesarlopes** [rehmatworks/stisla-laravel#6]
Hello,

I just did a clean installation and when trying to access the route:

 /public/admin/users

this error appeared:
403 This action is unauthorized.

The database is already populated and accessed with the demo data:

Demo Admin Login
Email: admin@example.com
Password: 1234

**Comment by rehmatworks** [comment]
Did you use the seeder to populate data or manually created the data? Looks like you haven't assigned the admin role to user. Seeding the database using provided seeders should not result in this issue.
