### ISSUE TITLE
Components not loading

### ISSUE THREAD

**Issue by dsamurai** [rehmatworks/stisla-laravel#7]
First thank you so much for taking the time to help with this. I'm a somewhat beginner with Vuejs, i happened to follow the same procedure as you did for the users component. Even after registering them, they still show up as unknown.

**Comment by rehmatworks** [comment]
Hello @dsamurai, did you compile the JS after writing your components? If errors are still there, can you share your code as a gist?

**Comment by dsamurai** [comment]
Hi @rehmatworks yes i did. And still tells me the same thing.

**Comment by rehmatworks** [comment]
I'm closing this issue as it doesn't fit as an issue. Please read the docs from VueJS carefully and compare your code precisely with mine.
